set(_CATKIN_CURRENT_PACKAGE "camera_pseudo")
set(camera_pseudo_VERSION "1.0.0")
set(camera_pseudo_MAINTAINER "Patrick Baumann <baumannpa@gmail.com>")
set(camera_pseudo_PACKAGE_FORMAT "1")
set(camera_pseudo_BUILD_DEPENDS "sensor_msgs" "rospy" "roscpp" "numpy" "cv_bridge")
set(camera_pseudo_BUILD_EXPORT_DEPENDS "sensor_msgs" "rospy" "roscpp" "numpy" "cv_bridge")
set(camera_pseudo_BUILDTOOL_DEPENDS "catkin")
set(camera_pseudo_BUILDTOOL_EXPORT_DEPENDS )
set(camera_pseudo_EXEC_DEPENDS "sensor_msgs" "rospy" "roscpp" "numpy" "cv_bridge")
set(camera_pseudo_RUN_DEPENDS "sensor_msgs" "rospy" "roscpp" "numpy" "cv_bridge")
set(camera_pseudo_TEST_DEPENDS )
set(camera_pseudo_DOC_DEPENDS )
set(camera_pseudo_URL_WEBSITE "")
set(camera_pseudo_URL_BUGTRACKER "")
set(camera_pseudo_URL_REPOSITORY "")
set(camera_pseudo_DEPRECATED "")