set(_CATKIN_CURRENT_PACKAGE "excercise_1")
set(excercise_1_VERSION "1.0.0")
set(excercise_1_MAINTAINER "Patrick Baumann <Patrick.Baumann@htw-berlin.de>")
set(excercise_1_PACKAGE_FORMAT "1")
set(excercise_1_BUILD_DEPENDS "roscpp" "rospy")
set(excercise_1_BUILD_EXPORT_DEPENDS "rospy" "roscpp")
set(excercise_1_BUILDTOOL_DEPENDS "catkin")
set(excercise_1_BUILDTOOL_EXPORT_DEPENDS )
set(excercise_1_EXEC_DEPENDS "rospy" "roscpp")
set(excercise_1_RUN_DEPENDS "rospy" "roscpp")
set(excercise_1_TEST_DEPENDS )
set(excercise_1_DOC_DEPENDS )
set(excercise_1_URL_WEBSITE "")
set(excercise_1_URL_BUGTRACKER "")
set(excercise_1_URL_REPOSITORY "")
set(excercise_1_DEPRECATED "")